apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: health-107-staging

images:
- digest: sha256:f870d2efe94b46b9b70c271f873fd4bc7bceccdbe6c305413d0e09795e335638
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: image-registry.openshift-image-registry.svc:5000/health-107-develop/health-107-record
